config/routes.rb
Rails.application.routes.draw do
root 'welcome#index'

resources :users

resources :callouts
resources :sessions, only: [:new, :create]

delete '/logout' => 'sessions#destroy', as: :logout
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/callout.rb
class Callout < ApplicationRecord
  belongs_to :user

  has_attached_file :calloutpic,
  styles: {medium: "300x300>", thumb: "100x100>"},
  default_url: "/images/avatar.jpg"

validates_attachment_content_type :calloutpic, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :callouts, :dependent => :destroy
    
    has_attached_file :profilepic,
    styles: {medium: "300x300>", thumb: "100x100>"},
    default_url: "/images/avatar.jpg"

validates_attachment_content_type :profilepic, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/callouts_controller.rb
class CalloutsController < ApplicationController
    def index
        # @callouts = Callout.all.order(created_at: :desc)
        name = "name ILIKE :query"
        tag = "tag ILIKE :query"
        city = "city ILIKE :query"
        query = {query: "%#{params[:query]}%"}
        @callouts = Callout.where("#{name} OR #{tag} OR #{city}", query).order(created_at: :desc)
    end

    def show
        @callout = Callout.find(params[:id])
        
    end
    def new 
        @callout = Callout.new
    end

    def create
        
        # Philippe's Method
        # @co = current_user.callouts.create(callout_params)
        
        # Option 2
        @callout = Callout.new(callout_params)
        @callout.user = current_user
        @callout.save
        redirect_to current_user

        end

    def destroy
        @callout = Callout.find(params[:id])
        @callout.destroy
        
        redirect_to callouts_path
    end 

    private 
    def callout_params
    params.require(:callout).permit(:name, :body, :city, :tag, :calloutpic)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user =User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = "Hey #{@user.name}!"
      redirect_to user_path(@user)
    else
      flash[:danger] = 'Incorrect email or password. Please try again.'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @thisuser = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_session_path
    else 
      flash[:danger] = "Nope"
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      flash[:danger] = "error"
      redirect_to new_user_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path
  end


private 
def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation, :profilepic)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @callouts = Callout.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/callouts_helper.rb
module CalloutsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/callouts/index.html.erb
<p>All Callouts</p>
<ul class="list-group">
    <form class="form-inline my-2 my-lg-0" action="<%= callouts_path %>" method="get">
        <input name="query" class="form-control mr-sm-2" type="text" placeholder="search offenders" aria-label="Search">
        <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
    </form>
<% @callouts.each do |c| %>

    <li class="list-group-item">
        <%= link_to callout_path(c) do %>
            <%= c.name %> ~ <%= c.city %> ~ <%= c.tag %> ~ <%= time_ago_in_words(c.created_at) %> ago
        <% end %>
    </li>

<% end %>
</ul>

app/views/callouts/new.html.erb
<h1>Fresh Callout</h1>
<p class="callout-form">
<%= form_for @callout do |f| %>
<div class="centers">
<%= f.text_field :name, placeholder: "callout"%>
<%= f.text_field :city, placeholder: "location" %>
<%= f.text_field :tag, placeholder: "tag" %>
</div>
</p>
<br>
<p>
<%= f.text_area :body, :cols => "30", :rows => "5", placeholder: "offense" %>
<%= f.submit "post" %>
<div class="centers"><%= f.file_field :calloutpic %></div>
</p>
<% end %>

app/views/callouts/show.html.erb
<div class="jumbotron">
    <h1 class="display-3"><%= @callout.name %></h1>
    <p class="lead">location: <%= @callout.city %></p>
    <p class="lead">tag: <%= @callout.tag %></p>
    <p class="lead"><%= @callout.body %></p>

    <hr class="my-4">
    <div><%= image_tag @callout.calloutpic.url(:medium) %></div>
    <p class="lead">
        <%= link_to "delete", callout_path(@callout), method: "delete", class:"btn btn-warning btn-lg"%>
    </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>pryx</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/partials/flash'  %>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
  <%= value %>
</div>
<% end %>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'pryx', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if logged_in? %>

            <li class="nav-item">
            <%= link_to 'new', new_callout_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'callouts', callouts_path, class: 'nav-link' %>
            <li class="nav-item">
                <%= link_to 'account', edit_user_path(current_user), class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'logout', logout_path, class: 'nav-link', method: 'delete' %>
                    </li>
                    
            <li class="nav-item" id="current-user">
                <%= link_to current_user.name, user_path(current_user) %>
            </li>
      
        <% else %>
            <li class="nav-item">
                <%= link_to 'Log In', new_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item"></li>
                <%= link_to 'Sign Up', new_user_path, class: 'nav-link' %>
            </li>
            <li class="nav-item"></li>
            <%= link_to "Callouts", callouts_path, class: 'nav-link' %>
        </li>
            
        </ul>
        <% end %>
    </div>
</nav>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<%= form_for @user, :html => {class: 'edit_user form-horizontal'} do |f| %>
<div class="row"><legend class="col-md-4 col-md-offset-4">Modify Account:</legend></div>
<fieldset>
    <div class="form-group">
        <%= f.label :name, 'Name*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :name, class: 'form-control', placeholder: 'update name' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :email, class: 'form-control', placeholder: 'update email' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password, class: 'form-control', placeholder: 'new password' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'reenter new password' %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <%= f.submit 'Update Account', class: 'btn btn-success' %>
            <%= link_to "Delete Account", user_path(current_user), method: 'delete', class: 'btn btn-danger' %>
            <%= f.file_field :profilepic %>
        </div>
    </div>
</fieldset>
<% end %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user, :html => {class: 'new_user form-horizontal'} do |f| %>
<div class="row"><legend class="col-md-4 col-md-offset-4">Create Account:</legend></div>
<fieldset>
    <div class="form-group">
        <%= f.label :name, 'Name*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :name, class: 'form-control', placeholder: 'user name' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :email, 'Email*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.text_field :email, class: 'form-control', placeholder: 'email' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password, 'Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password, class: 'form-control', placeholder: 'password' %>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation, 'Confirm Password*', class: 'col-md-4 control-label' %>
        <div class="col-md-5">
            <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'enter password again' %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
            <%= f.submit 'Create Account', class: 'btn btn-warning' %>
        </div>
    </div>
</fieldset>
<% end %>

app/views/users/show.html.erb
<h1>callouts from <%=@thisuser.name %></h1>

<div class="jumbotron">
    <div>
        <%= image_tag @thisuser.profilepic.url(:medium) %>
        <%= @thisuser.name %>
    </div>
    
    <% @thisuser.callouts.reverse.each do |c| %>
        <div class="card" style="width: 20rem;">
            <img class="card-img-top" src="<%= c.calloutpic.url(:medium) %>" alt="Card image cap">
            <div class="card-body">
                <h4 class="card-title"><%= c.name %></h4>
                <p class="card-text"><%= c.body %></p>
                <p><%= 'from ' + time_ago_in_words(c.created_at) + ' ago' %></p>
                <a href="#" class="btn btn-warning">delete</a>
            </div>
        </div>
    <% end %>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/welcome/index.html.erb
<h1>pryx</h1>
<br>

<p style="background:rgba(0, 0, 0, 0.4);">Correcting the world... one callout at a time.</p>